### ISSUE TITLE
Problems compiling on Ubuntu

### ISSUE THREAD

**Issue by greyeagle** [dbahrdt/oscar#29]
Hello,
after checking out the example page (and really liking what I see)  I wanted to test Oscar on my own machine. However I am stuck compiling.
I downloaded the complete structure. I found that some folders (namely with @ sign) were not downloaded so I downloaded them individually and put them in place.
I followed the readme and set CMAKE_GCC_VERSION_FOR_LTO=4.9 successfully after adding an older repository and installing the 4.9 version indeed. 

`cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/setup-lto.cmake -DCMAKE_BUILD_TYPE=ultra ../`

gives me the following errors:

> CMake Warning at liboscar/CMakeLists.txt:13 (find_package):
  By not providing "FindCGALSimple.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CGALSimple", but CMake did not find one.

  

> Could not find a package configuration file provided by "CGALSimple" with
  any of the following names:

>  CGALSimpleConfig.cmake
    cgalsimple-config.cmake

  >  Add the installation prefix of "CGALSimple" to CMAKE_PREFIX_PATH or set
  "CGALSimple_DIR" to a directory containing one of the above files.  If
  "CGALSimple" provides a separate development package or SDK, be sure it has
  been installed.
>  -- Looking for ragel
CMake Error at liboscar/vendor/sserialize/cmake/FindRagel.cmake:46 (MESSAGE):
  Could not find ragel
Call Stack (most recent call first):
  liboscar/vendor/sserialize/CMakeLists.txt:14 (find_package)

>  -- Configuring incomplete, errors occurred!
See also ".../oscar-master/build/CMakeFiles/CMakeOutput.log".
See also ".../oscar-master/build/CMakeFiles/CMakeError.log".
 

In the log file I find: 

>  Performing C++ SOURCE FILE Test HAVE_CPP17_COMPILER failed with the following output:
Change Dir: .../oscar-master/build/CMakeFiles/CMakeTmp

>  Run Build Command:"/usr/bin/make" "cmTC_b6de0/fast"
/usr/bin/make -f CMakeFiles/cmTC_b6de0.dir/build.make CMakeFiles/cmTC_b6de0.dir/build
make[1]: Entering directory '.../oscar-master/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_b6de0.dir/src.cxx.o
/usr/bin/g++-4.9    -DHAVE_CPP17_COMPILER   -std=c++17 -o CMakeFiles/cmTC_b6de0.dir/src.cxx.o -c .../oscar-master/build/CMakeFiles/CMakeTmp/src.cxx
g++-4.9: error: unrecognized command line option '-std=c++17'
CMakeFiles/cmTC_b6de0.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_b6de0.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_b6de0.dir/src.cxx.o] Error 1
make[1]: Leaving directory '.../oscar-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_b6de0/fast' failed
make: *** [cmTC_b6de0/fast] Error 2

>  Source file was:
int main() { return 0; }

I also get:
`g++ (gcc) --version` 
>  g++ (Ubuntu 7.3.0-27ubuntu1 18.04) 7.3.0
gcc (Ubuntu 7.3.0-27ubuntu1 18.04) 7.3.0

But I also have the 4.9 Versions installed (maybe I need a specific lib I am missing?).
I am on Ubuntu 18.04 LTS (bionic).

Any hint where to look will be highly appreciated.

**Comment by greyeagle** [comment]
I finally got around to doing what you have said. I found that I have a few conflicting libs on my installation so I worked from a fresh Ubuntu docker container. 
After finding all the necessary libs I could run cmake successfully. But now I have: 

`[ 82%] Linking CXX executable oscar-gui
[ 82%] Built target oscar-gui
osmpbf/osmpbf/CMakeFiles/osmpbf.dir/build.make:61: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:4120: recipe for target 'osmpbf/osmpbf/CMakeFiles/osmpbf.dir/all' failed
make[1]: *** [osmpbf/osmpbf/CMakeFiles/osmpbf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
Could you point me where to look? Thanks so much for your time!

**Comment by dbahrdt** [comment]
I've tested compiling oscar in a ubuntu chroot and it is working. I'll setup Docker to replicate your problem.

**Comment by dbahrdt** [comment]
Sorry for my late answer. Can you test the compilation using the docker file locate here: https://github.com/dbahrdt/oscar/blob/master/docker/ubuntu/Dockerfile?

**Comment by greyeagle** [comment]
No problem, I will not be in the office tomorrow, so I'll give it a go on Monday.

**Comment by greyeagle** [comment]
I can confirm I was able to compile with the docker file you provided. Thank's again for that! I will continue testing now. there are a lot of things going on in parallel right now on my end so please bear with me if I do not get back so very fast.

**Comment by dbahrdt** [comment]
In case you're simply interested in querying data sets you can find some at [http://data.oscar-web.de/](http://data.oscar-web.de/). If you want to create your own data sets then you can also check-out the [oscar-experiments](https://github.com/dbahrdt/oscar-experiments) repository and there the thesis-create.sh.
